import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function pricing() {
  return <h1>Pricing Page</h1>;
};

export default pricing;
