import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function contact() {
  return <h1>Contact Page</h1>;
};

export default contact;
